### ISSUE TITLE
Splunk forwarder installation failure

### ISSUE THREAD

**Issue by yangpeng-chn** [chef-cookbooks/chef-splunk#156]
### Cookbook version
6.0.0

### Chef-client version
15.6.10

### Platform Details
Redhat 7.x

### Scenario:
Failed to install splunk forwarder

### Steps to Reproduce:
Wrapper cookbook which includes `chef-splunk::default` recipe

### Expected Result:
Splunk forwarder to be installed without error.

### Actual Result:
Splunk forwarder was installed, but chef-client failed to run all the run list with the error below.

```
Using policy 'iset_splunk_forwarder' at revision '81d2fe6f2ea9ac01cfb6fadd0b773a508c62e6cd5e440ba18562c8768ad2ddc2'
resolving cookbooks for run list: ["chef-client::default@11.5.0 (7cb128f)", "chef-client::delete_validation@11.5.0 (7cb128f)", "iset_splunk::inst
all_forwarder@0.1.0 (7c04724)"]
Synchronizing Cookbooks:
  - chef-client (11.5.0)
  - chef-vault (4.0.0)
  - chef-splunk (6.0.0)
  - cron (6.2.2)
  - logrotate (2.2.2)
  - iset_splunk (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 30 resources
Recipe: chef-client::systemd_service
  * directory[/var/run/chef] action create (up to date)
  * directory[/var/cache/chef] action create (up to date)
  * directory[/var/lib/chef] action create (up to date)
  * directory[/var/log/chef] action create (up to date)
  * directory[/etc/chef] action create (up to date)
  * template[/etc/sysconfig/chef-client] action create (up to date)
  * directory[/etc/systemd/system] action create (up to date)
  * systemd_unit[chef-client.service] action create (up to date)
  * systemd_unit[chef-client.timer] action stop (up to date)
  * systemd_unit[chef-client.timer] action disable (up to date)
  * systemd_unit[chef-client.timer] action delete (up to date)
  * service[chef-client] action enable (up to date)
  * service[chef-client] action start (up to date)
Recipe: chef-client::delete_validation
  * file[/etc/chef/validation.pem] action delete (up to date)
Recipe: chef-splunk::user
  * group[splunk] action create
    - create group splunk
  * linux_user[splunk] action create
    - create user splunk
Recipe: chef-splunk::install_forwarder
  * splunk_installer[splunkforwarder] action run
    * remote_file[splunkforwarder-7.2.6-c0bf0f679ce9-linux-2.6-x86_64.rpm] action create
      - create new file /var/chef/cache/splunkforwarder-7.2.6-c0bf0f679ce9-linux-2.6-x86_64.rpm
      - update content in file /var/chef/cache/splunkforwarder-7.2.6-c0bf0f679ce9-linux-2.6-x86_64.rpm from none to 339ccb
      (file sizes exceed 10000000 bytes, diff output suppressed)
      - change mode from '' to '0644'
    * rpm_package[splunkforwarder] action install
      - install version 7.2.6-c0bf0f679ce9 of package splunkforwarder

  * execute[enable boot-start] action run
    - execute /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license
Recipe: chef-splunk::client
  * service[splunk] action start
    * Service status not available. Assuming a prior action would have installed the service.
    * Assuming status of not running.
    * Failed to determine status of service[splunk], using command /opt/splunkforwarder/bin/splunk status --answer-yes --no-prompt --accept-licen
se.
    * Assuming service would have been installed and is disabled
    - Would start service service[splunk]
Recipe: chef-splunk::service
  * execute[/opt/splunkforwarder/bin/splunk stop] action run (skipped due to not_if)
  * ruby_block[splunk_fix_file_ownership] action run (skipped due to not_if)
  * execute[/opt/splunkforwarder/bin/splunk stop] action run (skipped due to not_if)
Recipe: chef-splunk::client
  * service[splunk] action start
    - start service service[splunk]
  * service[splunk] action enable
    * Service status not available. Assuming a prior action would have installed the service.
    * Assuming status of not running.
    * Failed to determine status of service[splunk], using command /opt/splunkforwarder/bin/splunk status --answer-yes --no-prompt --accept-licen
se.
    * Assuming service would have been installed and is disabled
    - Would enable service service[splunk]
Recipe: chef-splunk::service
  * execute[/opt/splunkforwarder/bin/splunk stop] action run (skipped due to not_if)
  * ruby_block[splunk_fix_file_ownership] action run (skipped due to not_if)
  * execute[/opt/splunkforwarder/bin/splunk stop] action run (skipped due to not_if)
Recipe: chef-splunk::client
  * service[splunk] action enable

    ================================================================================
    Error executing action `enable` on resource 'service[splunk]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/systemctl --system enable splunk ----
    STDOUT:
    STDERR: Failed to execute operation: No such file or directory
    ---- End output of /usr/bin/systemctl --system enable splunk ----
    Ran /usr/bin/systemctl --system enable splunk returned 1

    Resource Declaration:
    ---------------------
    # In /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.6.10/lib/chef/dsl/declare_resource.rb

    159:         resource = declare_resource(type, name, created_at: created_at, run_context: run_context)
    160:         if resource_attrs_block

    Compiled Resource:
    ------------------
    # Declared in /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.6.10/lib/chef/dsl/declare_resource.rb:159:in `rescue in edit_resource'

    service("splunk") do
      provider Chef::Provider::Service::Systemd
      action [:start, :enable]
      updated true
      default_guard_interpreter :default
      declared_type :service
      cookbook_name "chef-splunk"
      recipe_name "client"
      supports {:status=>true, :restart=>true}
      stop_command "/opt/splunkforwarder/bin/splunk stop --answer-yes --no-prompt --accept-license"
      start_command "/opt/splunkforwarder/bin/splunk start --answer-yes --no-prompt --accept-license"
      restart_command "/opt/splunkforwarder/bin/splunk restart --answer-yes --no-prompt --accept-license"
      status_command "/opt/splunkforwarder/bin/splunk status --answer-yes --no-prompt --accept-license"
      service_name "splunk"
      running true
      enabled true
      masked false
    end

    System Info:
    ------------
    chef_version=15.6.10
    platform=redhat
    platform_version=7.3
    ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client

Recipe: chef-splunk::service
  * service[splunk] action start
    * Service status not available. Assuming a prior action would have installed the service.
    * Assuming status of not running.
    * Failed to determine status of service[splunk], using command /opt/splunkforwarder/bin/splunk status --answer-yes --no-prompt --accept-licen
se.
    * Assuming service would have been installed and is disabled
    - Would start service service[splunk]
  * execute[/opt/splunkforwarder/bin/splunk stop] action run (skipped due to not_if)
  * ruby_block[splunk_fix_file_ownership] action run (skipped due to not_if)
  * execute[/opt/splunkforwarder/bin/splunk stop] action run (skipped due to not_if)
  * service[splunk] action start
    - start service service[splunk]

Running handlers:
[2020-03-13T13:55:08+09:00] ERROR: Running exception handlers
Running handlers complete
[2020-03-13T13:55:08+09:00] ERROR: Exception handlers complete
Chef Infra Client failed. 11 resources updated in 10 seconds
[2020-03-13T13:55:08+09:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-03-13T13:55:08+09:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-03-13T13:55:08+09:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[splunk] (chef-splunk::client line 159) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/systemctl --system enable splunk ----
STDOUT:
STDERR: Failed to execute operation: No such file or directory
---- End output of /usr/bin/systemctl --system enable splunk ----
Ran /usr/bin/systemctl --system enable splunk returned 1
```
I have no idea where the command `/usr/bin/systemctl --system enable splunk` come from and 
If I run chef-client without changing anything after the above failure, it failed with different error at the task of enabling boot-start.

```
Recipe: chef-splunk::user
  * group[splunk] action create (up to date)
  * linux_user[splunk] action create (up to date)
  * linux_user[splunk] action create (up to date)
Recipe: chef-splunk::install_forwarder
  * splunk_installer[splunkforwarder] action run (up to date)
  * execute[enable boot-start] action run

    ================================================================================
    Error executing action `run` on resource 'execute[enable boot-start]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '8'
    ---- Begin output of /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license ----
    STDOUT:
    STDERR: Unable to create symlink='/etc/systemd/system/multi-user.target.wants/SplunkForwarder.service'
    : File exists
    ---- End output of /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license ----
    Ran /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license returned 8

    Resource Declaration:
Recipe: chef-splunk::user
  * group[splunk] action create (up to date)
  * linux_user[splunk] action create (up to date)
  * linux_user[splunk] action create (up to date)
Recipe: chef-splunk::install_forwarder
  * splunk_installer[splunkforwarder] action run (up to date)
  * execute[enable boot-start] action run

    ================================================================================
    Error executing action `run` on resource 'execute[enable boot-start]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '8'
    ---- Begin output of /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license ----
    STDOUT:
    STDERR: Unable to create symlink='/etc/systemd/system/multi-user.target.wants/SplunkForwarder.service'
    : File exists
    ---- End output of /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license ----
    Ran /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license returned 8

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef-splunk/recipes/install_forwarder.rb

     30: execute 'enable boot-start' do
     31:   user 'root'
     32:   command "#{splunk_cmd} enable boot-start --answer-yes --no-prompt#{license_accepted? ? ' --accept-license' : ''}"
     33:   creates '/etc/init.d/splunk'
     34: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef-splunk/recipes/install_forwarder.rb:30:in `from_file'

    execute("enable boot-start") do
      action [:run]
      default_guard_interpreter :execute
      command "/opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license"
      backup 5
      declared_type :execute
      cookbook_name "chef-splunk"
      recipe_name "install_forwarder"
      user "root"
      creates "/etc/init.d/splunk"
      domain nil
    end

    System Info:
    ------------
    chef_version=15.6.10
    platform=redhat
    platform_version=7.3
    ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client


Running handlers:
[2020-03-13T14:16:25+09:00] ERROR: Running exception handlers
Running handlers complete
[2020-03-13T14:16:25+09:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 04 seconds
[2020-03-13T14:16:25+09:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-03-13T14:16:25+09:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-03-13T14:16:25+09:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[enable boot-start] (chef-splunk::install_forwarder line 30) had
an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
---- Begin output of /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license ----
STDOUT:
STDERR: Unable to create symlink='/etc/systemd/system/multi-user.target.wants/SplunkForwarder.service'
: File exists
---- End output of /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license ----
Ran /opt/splunkforwarder/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license returned 8
```

It seems that:
1. It creates /etc/systemd/system/multi-user.target.wants/SplunkForwarder.service instead of /etc/init.d/* when it comes to forwarder, but it creats /etc/init.d/splunk when it was server.
2. enable boot-start twice for splunk server won't generate error, but it fails for splunk forwarder as it creates systemd file.

**Comment by yangpeng-chn** [comment]
Update:

After digging into the issue above, it turns out the `service `resource with `enable` action doesn't work in my case. But it works I were to install server...

```
service 'splunk' do
  action :enable
end
```

Error:
```
---- Begin output of /usr/bin/systemctl --system enable splunk ----
STDOUT:
STDERR: Failed to execute operation: No such file or directory
---- End output of /usr/bin/systemctl --system enable splunk ----
```

**Comment by haidangwa** [comment]
@yangpeng-chn In your last comment, are you saying that you enabled the server and also installed the universal forwarder? If so, that is not a supported Splunk installation. Splunk servers should never have both installed.

**Comment by haidangwa** [comment]
It appears the `enable boot-start` command needs to be different for the UF: https://docs.splunk.com/Documentation/Splunk/8.0.2/Admin/ConfigureSplunktostartatboottime#Enable_boot-start_on_machines_that_run_systemd

**Comment by yangpeng-chn** [comment]
> @yangpeng-chn In your last comment, are you saying that you enabled the server and also installed the universal forwarder? If so, that is not a supported Splunk installation. Splunk servers should never have both installed.

No, I installed them on different servers.

**Comment by yangpeng-chn** [comment]
> It appears the `enable boot-start` command needs to be different for the UF: https://docs.splunk.com/Documentation/Splunk/8.0.2/Admin/ConfigureSplunktostartatboottime#Enable_boot-start_on_machines_that_run_systemd

Yes, I had to tweak the code a bit and it appears different versions of FW have different results as well.

**Comment by haidangwa** [comment]
@yangpeng-chn I believe this is no longer an issue, as chef-splunk now does not use the `enable boot-start` command and sets up the sysV or systemd scripts natively. Please try the latest version, v6.2.7.  I will close this now, but feel free to reopen if your issue hasn't been resolved.
