### ISSUE TITLE
convert splunk_installer definition to Chef 12.5 custom resource

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/chef-splunk#58]
We should replace the definition with a custom resource in the style of Chef 12.5. This obviously can't happen until 12.5 is released.
- http://docs.chef.io/release/12-5/custom_resources.html
- docs.chef.io/release/12-5/definitions.html

**Comment by haidangwa** [comment]
Can someone please implement this?

**Comment by haidangwa** [comment]
@tas50 @jtimberman I do think this is more than an enhancement. It is causing anyone using chefspec to have a failed run. Reports have been made that demonstrate the failure of chefspec when a cookbook uses a chef definition instead (see https://github.com/zuazo/ssh_authorized_keys-cookbook/issues/14, for example).

My organization has a wrapper around this chef-splunk cookbook and we're not able to move forward, because chefspec fails for us.

Here is the chefspec snippet that we get:
```
  1) twdc_chef_monitoring::splunk_nginx_monitors created splunk monitor
     Failure/Error:
       ChefSpec::ServerRunner.new do |node, server|
         create_data_bag_item(server, 'vault', 'splunk_kitchen')
         create_environments(server)
         node.chef_environment = 'kitchen'
       end.converge(described_recipe)
     
     NoMethodError:
       undefined method `params' for nil:NilClass
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/dsl/definitions.rb:31:in `evaluate_resource_definition'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/dsl/definitions.rb:14:in `splunk_installer'
     # /tmp/cookbooks/chef-splunk/recipes/install_forwarder.rb:20:in `from_file'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/mixin/from_file.rb:34:in `instance_eval'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/mixin/from_file.rb:34:in `from_file'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/cookbook_version.rb:199:in `load_recipe'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/run_context.rb:350:in `load_recipe'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/run_context.rb:306:in `block in include_recipe'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/run_context.rb:305:in `each'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/run_context.rb:305:in `include_recipe'
     # ./vendor/bundle/ruby/2.5.0/gems/chef-14.12.9/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
```
