### ISSUE TITLE
Remove dependency on chef-vault

### ISSUE THREAD

**Issue by tmaier** [chef-cookbooks/chef-splunk#72]
I understand why chef-vault has been used here.
But chef-vault is just one of many solutions for the problem to solve.

The splunk cookbook is a typical application cookbook. It should do it's job and stop right there.
Each user should then follow the wrapper cookbook pattern to implement organization specific decisions. For example weather or not to use chef-vault...

It would be great if this cookbook would remove it's dependency to chef-vault.
- The sensitive attributes should be stored in node attributes.
- A wrapper cookbook would then use `node.run_state[:my_splunk_secret’] = ‘…’` to set these sensitive attributes only for the runtime.

**Comment by filltr** [comment]
PLease!

**Comment by shapeofarchitect** [comment]
I would strongly  recommend above , as there has been a lot of issues with this dependency , the latest issue I am facing now is that AWS OpsWorks with chef-splunk and it doesn't support encrypted data bags too.

```

================================================================================
Recipe Compile Error in /var/chef/runs/09193be9-9c61-47dc-8e32-64e179e1ba17/local-mode-cache/cache/cookbooks/chef-splunk/recipes/default.rb
================================================================================
 
Net::HTTPServerException
------------------------
404 "Not Found"
 
Cookbook Trace:
---------------
/var/chef/runs/09193be9-9c61-47dc-8e32-64e179e1ba17/local-mode-cache/cache/cookbooks/chef-vault/libraries/helpers.rb:38:in `chef_vault_item'
/var/chef/runs/09193be9-9c61-47dc-8e32-64e179e1ba17/local-mode-cache/cache/cookbooks/chef-splunk/recipes/setup_auth.rb:21:in `from_file'
/var/chef/runs/09193be9-9c61-47dc-8e32-64e179e1ba17/local-mode-cache/cache/cookbooks/chef-splunk/recipes/client.rb:81:in `from_file'
/var/chef/runs/09193be9-9c61-47dc-8e32-64e179e1ba17/local-mode-cache/cache/cookbooks/chef-splunk/recipes/default.rb:29:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/09193be9-9c61-47dc-8e32-64e179e1ba17/local-mode-cache/cache/cookbooks/chef-vault/libraries/helpers.rb:
 
31:    # +node['chef-vault']['databag_fallback']+.
32:    # @example
33:    # item = chef_vault_item('secrets', 'bacon')
34:    # log 'Yeah buddy!' if item['_default']['type']
35:    # @param [String] bag Name of the data bag to load from.
36:    # @param [String] id Identifier of the data bag item to load.
37:    def chef_vault_item(bag, id)
38>>     if ChefVault::Item.vault?(bag, id)
39:        ChefVault::Item.load(bag, id)
40:      elsif node['chef-vault']['databag_fallback']
41:        data_bag_item(bag, id)
42:      else
43:        raise "Trying to load a regular data bag item #{id} from #{bag}, and databag_fallback is disabled"
44:      end
45:    end
46:  
47:    # Helper method which provides an environment wrapper for a data bag.
 
Platform:
---------
x86_64-linux




================================================================================
Recipe Compile Error in /var/chef/runs/0a6f8712-ddf0-4b86-b2bf-5a290875e2ec/local-mode-cache/cache/cookbooks/chef-splunk/recipes/default.rb
================================================================================
 
Net::HTTPServerException
------------------------
404 "Not Found"
 
Cookbook Trace:
---------------
/var/chef/runs/0a6f8712-ddf0-4b86-b2bf-5a290875e2ec/local-mode-cache/cache/cookbooks/chef-vault/libraries/helpers.rb:38:in `chef_vault_item'
/var/chef/runs/0a6f8712-ddf0-4b86-b2bf-5a290875e2ec/local-mode-cache/cache/cookbooks/chef-splunk/recipes/setup_auth.rb:21:in `from_file'
/var/chef/runs/0a6f8712-ddf0-4b86-b2bf-5a290875e2ec/local-mode-cache/cache/cookbooks/chef-splunk/recipes/client.rb:81:in `from_file'
/var/chef/runs/0a6f8712-ddf0-4b86-b2bf-5a290875e2ec/local-mode-cache/cache/cookbooks/chef-splunk/recipes/default.rb:29:in `from_file'
 
Relevant File Content:
----------------------
/var/chef/runs/0a6f8712-ddf0-4b86-b2bf-5a290875e2ec/local-mode-cache/cache/cookbooks/chef-vault/libraries/helpers.rb:
 
31:    # +node['chef-vault']['databag_fallback']+.
32:    # @example
33:    # item = chef_vault_item('secrets', 'bacon')
34:    # log 'Yeah buddy!' if item['_default']['type']
35:    # @param [String] bag Name of the data bag to load from.
36:    # @param [String] id Identifier of the data bag item to load.
37:    def chef_vault_item(bag, id)
38>>     if ChefVault::Item.vault?(bag, id)
39:        ChefVault::Item.load(bag, id)
40:      elsif node['chef-vault']['databag_fallback']
41:        data_bag_item(bag, id)
42:      else
43:        raise "Trying to load a regular data bag item #{id} from #{bag}, and databag_fallback is disabled"
44:      end
45:    end

 ```

**Comment by devlinrcg** [comment]
Same as @shapeofarchitect

**Comment by haidangwa** [comment]
I don't like the idea of storing sensitive data in node attribtues; especially ones where they are to be encrypted by chef-vault or by encrypted data bags. Doing so defeats the purpose of encryption. Cookbooks that have done this imply another process to remove these node attributes from the node data before it gets uploaded back to the chef server at the end of successful chef runs. I think the cookbook should use chef's built-in encrypted data bag and rid of chef-vault altogether.

**Comment by bby-bishopclark** [comment]
It's a great idea to allow the implementer the choice of back-ends.

**Comment by bby-bishopclark** [comment]
Careful:  Since #120 was just declined, if we fixate on chef-vault then this cookbook may *no longer* be usable in an air-gapped environment.  This would make the emerging standard for PCI an environment too secure for chef/splunk, and it's not a space where I think Splunk can afford to be non-dominant.

**Comment by haidangwa** [comment]
Chef 13.4 now includes the chef-vault gem, so this should no longer be an issue. v2.0.0 of this cookbook also now requires `chef_version '>= 13.11'`. Chef 13 reached EOL as of 4/30/2019, as well.

https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#chef-vault-is-now-included
